# Uncomment the next line to define a global platform for your project
# platform :ios, '10.3'

target 'HyLionPost' do
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Alamofire', '~> 4.4'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HyLionPost

  target 'HyLionPostTests' do
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Alamofire', '~> 4.4'
    inherit! :search_paths
    # Pods for testing
  end

end
